name: test
description: "A Flutter Demo For How To Use alghwabli_easy_router"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  alghwalbi_easy_router: #^1.0.3
    path: C:\Users\ahmed\Desktop\workspace\alghwalbi_easy_router
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
